server:
  port:8095

spring:
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/discover/eureka